DATALOADER:
  TRAIN_X:
    SAMPLER: "RandomDomainSampler"
    BATCH_SIZE: 30
  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 6
  TEST:
    BATCH_SIZE: 30
  K_TRANSFORMS: 2

OPTIM:
  NAME: "sgd"
  LR: 0.001
  MAX_EPOCH: 90
  RAMPUP_ITRS: 10000

TRAINER:
  CDAC:
    STRONG_TRANSFORMS: ["randaugment", "normalize"]