DATALOADER:
  TRAIN_X:
    SAMPLER: "RandomDomainSampler"
    BATCH_SIZE: 64
  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 192
  TEST:
    BATCH_SIZE: 200
  K_TRANSFORMS: 2

OPTIM:
  NAME: "sgd"
  LR: 0.001
  MAX_EPOCH: 60
  RAMPUP_ITRS: 10000
  LR_SCHEDULER: "cosine"

TRAINER:
  CDAC:
    STRONG_TRANSFORMS: ["randaugment", "normalize"]