DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 16
  TEST:
    BATCH_SIZE: 16
  NUM_WORKERS: 16
  K_TRANSFORMS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 20
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 5
  WARMUP_TYPE: "linear"
  WARMUP_CONS_LR: 1e-5
  WEIGHT_DECAY: 5e-4

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

Adapter:
  Layer_ID: [0,1,2,3,4,5,6,7,8,9,10,11]
  Scale: -1.0
  Down_Rate: 384
  Attn: True
  MLP: True
  Visual: True
  Text: True

LLM:
  PATH: "./descriptions"
  Num_desc: 50
  Desc_Per_Batch: 8 # for imagenet, set to 4 to prevent OOM